apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-app-ingress
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: react.local 
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: react-app-svc
                port:
                  number: 80
