apiVersion: v1
kind: Service
metadata:
  name: react-app-nodeport-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
