apiVersion: v1
kind: Service
metadata:
  name: react-app-svc
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: react-app
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
