apiVersion: v1
kind: Service
metadata:
  name: react-app-svc
  labels:
    app.kubernetes.io/name: react-app
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: react-app
    meta.helm.sh/release-namespace: react-app
spec:
  selector:
    app: react-app
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
