apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-app.fullname" . }}
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP # Change the service type as needed (e.g., NodePort, LoadBalancer)
